services:
  video-trimmer:
    build:
      context: .
      dockerfile: Dockerfile
    image: trimvideo-app:latest
    hostname: trimvideo.com
    ports:
      - "443:443"
    volumes:
      - ./certificates:/app/certificates:ro
    environment:
      HOSTNAME: "0.0.0.0"
    restart: unless-stopped
