export const KEYBOARD_SHORTCUTS = {
  PLAY_PAUSE: ' ', // Space
  FRAME_BACKWARD: 'ArrowLeft',
  FRAME_FORWARD: 'ArrowRight',
  SECOND_BACKWARD: 'Shift+ArrowLeft',
  SECOND_FORWARD: 'Shift+ArrowRight',
  SET_IN_POINT: 'i',
  SET_OUT_POINT: 'o',
  GOTO_IN_POINT: 'Home',
  GOTO_OUT_POINT: 'End',
  PREVIEW: 'a',
} as const;

export const KEYBOARD_SHORTCUT_LABELS = {
  [KEYBOARD_SHORTCUTS.PLAY_PAUSE]: 'Space',
  [KEYBOARD_SHORTCUTS.FRAME_BACKWARD]: '←',
  [KEYBOARD_SHORTCUTS.FRAME_FORWARD]: '→',
  [KEYBOARD_SHORTCUTS.SECOND_BACKWARD]: 'Shift + ←',
  [KEYBOARD_SHORTCUTS.SECOND_FORWARD]: 'Shift + →',
  [KEYBOARD_SHORTCUTS.SET_IN_POINT]: 'I',
  [KEYBOARD_SHORTCUTS.SET_OUT_POINT]: 'O',
  [KEYBOARD_SHORTCUTS.GOTO_IN_POINT]: 'Home',
  [KEYBOARD_SHORTCUTS.GOTO_OUT_POINT]: 'End',
  [KEYBOARD_SHORTCUTS.PREVIEW]: 'A',
} as const;

// 타임라인 탐색 상수
export const FRAME_STEP = 1 / 30; // 30fps 기준 1프레임
export const SECOND_STEP = 1; // 1초
